version: '2.1'
services:
  rabbitmq:
    image: "rabbitmq:3.6.10"
    restart: 'no'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
  server:
    build: .
    restart: 'no'
    depends_on:
      - rabbitmq
    ports:
      - 8080:8080
